### PR TITLE
Setting up backup

### LINKED ISSUE #9: Implement WhatsApp backup flow
WhatsApp has an option to redirect to the app with a message field. We should let people do that, and then prompt them to send a message to themselves. WhatsApp is a very good E2E encrypted store.

As far as I can tell, Signal (using "Note to self") and Telegram (using "Saved Messages") do not implement this flow. So we should continue to use the copy data store method for people who want to use those.

### LINKED ISSUE #16: Implement copy data store button properly
- [x] Copy data with link

Right now on nfctap.xyz, when clicking on the copy data store button, on Safari and other browsers there is no toast notification / alert that the user has added their data store to their clipboard. We should fix this for the next version. This should be debugged and tested across

- [x]  Safari
- [x]  Chrome
- [x]  Brave

And any other easily downloadable browsers (Firefox?)

### LINKED ISSUE #17: New passes set up for Apple/Google wallet
Based on new logos and styling, set up a new wallet pass for apple and google wallet.

Both
- [x] Check if we can list out emojis on top line
  - [x] What is the limit on # of emojis
    
Apple
  - [x] Change format
  - [x] Replace all images
    - [x] Strip image
    - [x] Logo
  - [x] Remove QR code
  - [x] Make sure recovery link is clickable
  - [x] Change colors
  - [x] Test on 2 phones
    - [x] Properly renders
    - [x] Properly updates

Android
  - [x] Fix wallet UUID code
  - [x] Setup new layout in Wallet API page
  - [x] Add emojis to pass
  - [x] Fix updating code

### LINKED ISSUE #18: Need to properly error handle `GaxiosError: Wallet Object not found` on server
If user doesn't actually add a pass to Google Wallet, then when they try to update later, the server will error. In that case, we should actually just try and make them a new pass again instead of just failing.

### LINKED ISSUE #29: Compressed backups
Previously we were storing entire raw Sigmojis in the backup url, which quickly met the url size cap. We need to find a way to more efficiently store a Jubmoji backup, especially given that we will have 200 cards

- [x] More succinct serialization of Jubmojis
  - Currently just use serialized PCD, but this was already breaking the pass at >10 Sigmojis
  - Should use compressed version of signature and some encoding (likely base64 to start out with)
  - Could potentially use an emoji encoding for thematic coherence. But I wonder if that could just be more confusing lol
- [x] Test cases for succinct serialization + deserialization

### LINKED ISSUE #38: Restore flow + ensuring collections are merged upon backup
Description
  - Users may collect a new jubmoji and realize they need to restore their old data
  - Shouldn't erase their old collection
  - Depends on #29
 
Tasks
- [x] Merging collection functions
- [x] Implemented into restore flow
- [x] URIDecode collection
- [x] Vanilla test cases
  - [x] Apple
  - [x] Android
  - [x] Copy data store
- [x] Override test cases
  - [x] Apple
  - [x] Android
  - [x] Copy data store

### PR DESCRIPTION
**Pull request by vb7401**
- Closes #17
- Closes #18
- Closes #16 
- Closes #29
- Closes #38
- Closes #9

### CODE REVIEW

File: apps/jubmoji-quest/src/components/GoogleWalletButton.tsx [hunk 1]
```diff
@@ -2,79 +2,82 @@ import { loadBackupState, saveBackupState } from "../lib/localStorage";
...
-      });
-    } else if (!updateBackup) {
-      saveBackupState({
-        type: "google",
-        serialNum: serial,
-      });
-      window.location.href = saveUrl;
+    if (updateUrl) {
+      const response = await fetch(updateUrl);
+      if (response.status === 200) {
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/components/GoogleWalletButton.tsx:70]: What does it mean if the response is not 200? In this case, should we run the saveBackupState flow below?

File: apps/jubmoji-quest/src/pages/api/generateApplePass.ts [hunk 2]
```diff
@@ -36,7 +31,9 @@ export default async function handler(
     });
   }
 
-  if (parseInt(number as string) > COLLECTION_SIZE) {
+  const serializedJubmojis = collection.toString().split(",");
+
+  if (serializedJubmojis.length > COLLECTION_SIZE) {
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/pages/api/generateApplePass.ts:36]: What is the point of this check? Is there a reason we need to handle this edge case where a user sends us 500 Jubmojis to generate a pass with?

File: apps/jubmoji-quest/src/pages/api/models/sigmoji.pass/pass.json [hunk 3]
```diff
@@ -3,36 +3,32 @@
   "passTypeIdentifier": "pass.com.example.jubmoji",
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/pages/api/models/sigmoji.pass/pass.json:3]: This file is still in sigmoji.pass folder, can we change that

File: apps/jubmoji-quest/src/pages/collect/index.tsx [hunk 4]
```diff
@@ -163,13 +162,17 @@ export default function CollectJubmojiPage() {
         jubmojiCollectionCards,
         sig.pubKeyIndex
       );
+      await addJubmoji(realJubmoji);
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/pages/collect/index.tsx:165]: Unrelated to this PR, but do we have a ticket to create a UX for collection when users already have that Jubmoji in their wallet?

File: apps/jubmoji-quest/src/pages/recover/index.tsx [hunk 5]
```diff
@@ -0,0 +1,117 @@
...
+        return;
+      }
+      const succinctSerialization = decodeURIComponent(
+        succinctSerializationURI
+      );
+      const recoveredJubmojis = succinctDeserializeJubmojiList(
+        succinctSerialization
+      );
+
+      const unionJubmojis = new Set([...recoveredJubmojis, ...jubmojis]);
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/pages/recover/index.tsx:46]: nit: this could be a helper function in `localStorage.ts`

File: apps/jubmoji-quest/src/pages/recover/index.tsx [hunk 6]
```diff
@@ -0,0 +1,117 @@
...
+      const unionJubmojisArray = Array.from(unionJubmojis);
+
+      // make sure we only keep the lowest nonce for each pubKeyIndex
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/pages/recover/index.tsx:49]: Any reason we go lowest instead of say, keeping the one in their current localStorage first?

File: packages/jubmoji-api/test/util/serialize.test.ts [hunk 7]
```diff
@@ -0,0 +1,79 @@
+import {
+  serializeJubmojiList,
+  deserializeJubmojiList,
+  succinctSerializeJubmojiList,
+  succinctDeserializeJubmojiList,
+} from "../../src/util/serialize";
+import { Jubmoji } from "../../src/types";
+
+describe("serialization and deserialization should not lose data", () => {
```
Comment (AndrewCLu) [inline packages/jubmoji-api/test/util/serialize.test.ts:9]: test! <3

**Review by AndrewCLu — COMMENTED** [review]
Overall flow looks good, left a few minor comments. Still need to test full Apple Wallet flow so let's merge once thats fixed. Side note, after these changes we should be able to Ctrl + F `sigmoji` in the repo and find nothing right?

File: apps/jubmoji-quest/src/pages/collect/index.tsx (hunk 4 above)
Comment (vb7401) [reply apps/jubmoji-quest/src/pages/collect/index.tsx:165]: #77

File: apps/jubmoji-quest/src/lib/localStorage.ts [hunk 8]
```diff
@@ -21,6 +21,29 @@ export const writeJubmojis = async (jubmojis: Jubmoji[]): Promise<void> => {
   window.localStorage["jubmojis"] = serialized;
 };
 
+export const unionJubmojisUniquePubKey = async (
```
Comment (AndrewCLu) [inline apps/jubmoji-quest/src/lib/localStorage.ts:24]: Rename to `unionJubmojisByPubKey`

**Review by AndrewCLu — APPROVED** [review]
LGTM
